config/routes.rb
Rails.application.routes.draw do

  post 'post/vote' => 'votes#create'

  resources :communities do
    resources :posts
  end

  get 'u/:username' => 'public#profile', as: :profile

  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'public#index'
  resources :subscriptions
  resources :comments, only: [:create]

  
  
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :subscriptions
  has_many :communities, through: :subscriptions
  validates_presence_of :first_name, :last_name, :username
  def full_name
    "#{first_name} #{last_name}"
  end
  has_many :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :account
  validates_presence_of :message, :account_id , :post_id
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :account
  has_many :posts
  has_many :subscriptions
  validates_presence_of :url, :name, :rules
  has_many :subscribers, through: :subscriptions, source: :account
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :account
    belongs_to :community
    validates_presence_of :title, :body, :account_id, :community_id
    has_many :comments

    def score
      upvotes.to_i - downvotes.to_i
    end
  end
  

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :account
  belongs_to :community
  validates_uniqueness_of :community_id, scope: :account_id
end

app/models/vote.rb
class Vote < ApplicationRecord
    belongs_to :account
    belongs_to :post
    validates_uniqueness_of :account_id, scope: :post_id

    after_create :increment_vote
    after_destroy :decrement_vote

    private
    
    def increment_vote
        field = self.upvote ? :upvotes : :downvotes
        Post.find(self.post_id).increment(field).save
    end

    def decrement_vote
        field = self.upvote ? :upvotes : :downvotes
        Post.find(self.post_id).decrement(field).save
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    
    protect_from_forgery

    # if user is logged in, return current_user, else return guest_user
    def current_or_guest_user
      if current_user
        if session[:guest_user_id] && session[:guest_user_id] != current_user.id
          logging_in
          # reload guest_user to prevent caching problems before destruction
          guest_user(with_retry = false).try(:reload).try(:destroy)
          session[:guest_user_id] = nil
        end
        current_user
      else
        guest_user
      end
    end
  
    # find guest_user object associated with the current session,
    # creating one as needed
    def guest_user(with_retry = true)
      # Cache the value the first time it's gotten.
      @cached_guest_user ||= User.find(session[:guest_user_id] ||= create_guest_user.id)
  
    rescue ActiveRecord::RecordNotFound # if session[:guest_user_id] invalid
       session[:guest_user_id] = nil
       guest_user if with_retry
    end
  

  private

  def create_guest_user
    u = User.new(:first_name => "guest_#{Time.now.to_i}#{rand(100)}", :last_name => "guest_#{Time.now.to_i}#{rand(100)}", :username => "guest_#{Time.now.to_i}#{rand(100)}")
    u.save!(:validate => false)
    session[:guest_user_id] = u.id
    u
  end
    

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new comment_params
    @comment.account_id = current_or_guest_account.id

    respond_to do |format|
      format.js {
        if @comment.save
          @comments = Comment.where(post_id: @comment.post_id)
          render 'comments/create'
        end
      }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :post_id)
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :authenticate_account!, except: %i[index show]

  def index
    @communities = Community.all
  end

  def show
    set_community
    @posts = @community.posts.limit(20).sort_by{|p| p.score}.reverse
    @subscribers_count = if @community.subscribers.present?
                           @community.subscribers.count
                         else
                           0
                         end
    @is_subscribed = if account_signed_in?
                       Subscription.where(community_id: @community.id,
                                          account_id: current_account.id).any?
                     else
                       false
                     end
    @subscription = Subscription.new
  end

  def new
    @community = Community.new
  end

  def create
    @community = Community.new(community_values)
    @community.account_id = current_account.id
    if @community.save
      redirect_to communities_path
    else
      render new
    end
  end

  private

  def set_community
    @community = Community.find(params[:id])
  end

  def community_values
    params.require(:community).permit(:name, :url, :rules)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

 
  def index
    @posts = Post.all
  end

  def show
    set_post
    @comment = Comment.new
  end

  def new
    @community = Community.find(params[:community_id])
    @post = Post.new
  end

  def create
    @post = Post.new(post_values)
    @post.account_id = current_or_guest_account.id
    @post.community_id = params[:community_id]
    if @post.save
      redirect_to community_path(@post.community_id)
    else
      @community = Community.find(params[:community_id])
      render new
    end
  end


  private

def set_post
  @post = Post.includes(:comments).find(params[:id])
end
  
  def post_values
    params.require(:post).permit(:title,:body)
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController


    
def index
    @communities = Community.all.limit(5)
    @posts = Post.limit(20).sort_by{|p| p.score}.reverse
end

def profile
    @profile = Account.find_by_username params[:username]
    @posts = @profile.posts
end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_account!
  
    def create
      @subscription = Subscription.new(subscription_params)
      @subscription.account_id = current_account.id
      @subscription.save
      redirect_to community_path(@subscription.community_id)
    end
  
 
    private
  
    def subscription_params
      params.require(:subscription).permit(:community_id)
    end

  end
  

app/controllers/votes_controller.rb
class VotesController < ApplicationController
 
 
  def create
    
    vote = Vote.new
    post_id = params[:post_id]
    vote.post_id = params[:post_id]
    vote.upvote = params[:upvote]
    vote.account_id = current_or_guest_account.id
    existing_vote = Vote.where(account_id: current_or_guest_account.id, post_id: post_id)
    respond_to do |format|
      format.js do
        if existing_vote.size > 0
          existing_vote.first.destroy
        else
           vote.save
        end
        @post = Post.find(post_id)
        render 'votes/create'
      end
    end
  end

  private

  def vote_params
    params.require(:vote).permit(:upvote, :post_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/comments/create.js.erb
$("#post-comments").html("<%= escape_javascript(render "posts/comments", comments: @comments)%>")

app/views/communities/_form.html.erb
<%= form_with model: @community do |form| %>
<div class="form-group">
  <%= form.label :name, "Name" %>
  <%= form.text_field :name, class: "form-control"%>

</div>
<div class="form-group">
  <%= form.label :url, "Url" %>
  <%= form.text_field :url, class: "form-control"%>

</div>
<div class="form-group">
  <%= form.label :rules, "Rules" %>
  <%= form.text_area :rules, class: "form-control"%>
  
</div>
<%= form.submit %>
<%end%>

app/views/communities/_subscribe.html.erb
<%= form_with model: @subscription do |form|%>
<%= form.hidden_field :community_id, value: community_id%>
<%= form.submit "เข้าร่วมเป็นสมาชิกห้อง", class: "btn btn-warning " %>

<% end%>

app/views/communities/create.html.erb
<h1>Communities#create</h1>
<p>Find me in app/views/communities/create.html.erb</p>

app/views/communities/index.html.erb
<% if account_signed_in? %>
  <div class="float-right">
    <%= link_to "สร้างห้องใหม่", new_community_path, class: "btn btn-outline-primary ml-3"%>
  </div>
<% end %>
<% if @communities.size > 0 %>
  <% @communities.each do |community|%>
    <div class="card">
    <div class="card-header">
      <%= link_to community.name, community_path(community) %>
      </div>
      <div class="card-body">
      <%= community.rules %>
       </div>
    </div>
  <% end %>
<% else%>
  <p>No community to display</p>
<% end %>

app/views/communities/new.html.erb
<h2>สร้างห้องใหม่</h2>

<%= render "communities/form"%>

app/views/communities/show.html.erb
<div class="card">
  <div class="card-header">
    <%= @community.name %>
  </div>
  <div class="card-body">
    <%= simple_format @community.rules %>
 
    <%= render "communities/subscribe", community_id: @community.id %>
  </div>
  <div class="card-footer">
    จำนวนสมาชิกในห้องมีทั้งหมด <%= @subscribers_count %> คน
  </div>
</div>
<div class="mt-3 mb-3">
  <%= link_to "ตั้งกระทู้ใหม่", new_community_post_path(@community), class: "btn btn-info" %>
</div>
<% @posts.each do |post|%>
  <div class="card mb-3">
    <div class="card-header">
      <%= link_to post.title, community_post_path(@community, post) %>
    </div>
    <div class="card-body">
      <%= truncate post.body, length: 200 %>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
    <br>
    <footer class="footer bg-info">
      <div class="container text-center ">
        <span class="text-white">Copyright 2021 ARATORI, All Rights Reserved.</span>
      </div>
    </footer>

app/views/layouts/_header.html.erb
<nav class="navbar bg-info">
  <div class="container">
    <ul class="nav mx-auto bg-info">
      <%= link_to "Alert Channel" , root_path, class: 'text-white shadow-none', style: "font-size: xx-large; outline: none !important;" %>
    </ul>
  </div>
</nav>
<nav class="navbar navbar-expand-lg navbar-white bg-white">
  <div class="container">
    <%= link_to "สนทนาโดยไม่ต้องสมัครสมาชิก ภาษาญี่ปุ่น อนิเมะ สัพเพเหระ", root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if account_signed_in?%>
          <div class="dropdown">
            <button class="btn  dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_account.username%>
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
              <%= link_to profile_path(current_account.username), class: "dropdown-item" do %>
              <%= fa_icon 'user'%> ข้อมูลส่วนบุคคล
              <% end %>
              <%= link_to edit_account_registration_path, class: "dropdown-item" do%>
              <%= fa_icon 'edit'%> ตั้งค่า
              <% end %>
              <%= link_to destroy_account_session_path, class: "dropdown-item", method: :delete do%>
              <%= fa_icon 'sign-out'%> ออกจากระบบ
              <% end %>
            </div>
          </div>
        <% else%>
          <li class="nav-item">
            <%= link_to "สมัครสมาชิก", new_account_registration_path, class: "btn  btn-xs mr-1"%>
          </li>
          <li class="nav-item">
            <%= link_to "เข้าสู่ระบบ", new_account_session_path, class: "btn  btn-xs"%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alert Channel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header"%>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer"%>
  </body>
</html>

app/views/posts/_comments.html.erb
<% comments.each do |comment|%>
<div class="card mb-3">
  <div class="card-header">
    <% if comment.account.username%>
    <%= link_to comment.account.username, profile_path(comment.account.username) %>
    <% else %>
    <%=comment.account.email%>
    <% end %>
  </div>
  <div class="card-body">
    <%= comment.message %>
  </div>
</div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with model: [@community, @post] do |form| %>
<div class="form-group">
  <%= form.label :title, "Title" %>
  <%= form.text_field :title, class: "form-control"%>

</div>
<div class="form-group">
  <%= form.label :body, "Body" %>
  <%= form.text_area :body, class: "form-control"%>

</div>

<%= form.submit %>
<%end%>

app/views/posts/_list.html.erb
  <% posts.each do |post|%>
  <div class="row">
    <div class="col-11">
      <div class="card mb-3">
        <div class="card-header">
          <%= link_to post.title, community_post_path(post.community_id, post), class: "text-xl mb-1" %>
          <small class="font-weight-bold ml-auto"> ตั้งโดย 
          <% if post.account.username%>
          <%= link_to post.account.username, profile_path(post.account.username)%>
<%else%>
<%= post.account.email%>
<%end%>
          เมื่อ <%= post.created_at %> ห้อง <%= link_to post.community.name, community_path(post.community), class: "ml-auto" %> </small>
        </div>
        <div class="card-body">
          <p class="card-text"><%= truncate post.body, length: 200 %></p>
        </div>
      </div>
    </div>
    <div class="col-1 text-center">
      <div id="vote-actions-<%= post.id%>" class="vote" data-id="<%= post.id%>" >
        <div class="fa fa-arrow-up upvote"> </div>
        <div class="font-weight-bold score"><%= post.score%></div>
        <div class="fa fa-arrow-down downvote"> </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h2>แก้ไขกระทู้</h2>

<%= render "posts/form"%>

app/views/posts/new.html.erb
<h2>ตั้งกระทู้ใหม่</h2>

<%= render "posts/form"%>

app/views/posts/show.html.erb
 
<div class="row">
  <div class="col-11">
    <div class="card mb-3">
      <div class="card-header bg-warning font-weight-bold">
        <%= @post.title %>
      </div>
      <div class="card-body">
        <%= @post.body %>
      </div>
    </div>
  </div>
  <div class="col-1 text-center">

<div class="card mb-3">
      <div class="card-header bg-white font-weight-bold">

    <div id="vote-actions-<%= @post.id%>" class="vote" data-id="<%= @post.id%>" >
      <div class="fa fa-arrow-up upvote"> </div>
      <div class="font-weight-bold score"><%= @post.score%></div>
      <div class="fa fa-arrow-down downvote"> </div>
    </div>

 </div>
    </div>

  </div>
</div>
<div id="post-comments" class="mb-3">
  <%= render "posts/comments", comments: @post.comments%>
</div>
<%= form_for @comment, remote: true do |form|%>
  <%= form.hidden_field :post_id, value: @post.id%>
  <div class="card mb-3">
    <div class="card-header">
      <%= form.label :message, "ความคิดเห็น" %>
    </div>
    <div class="card-body">
      <%= form.text_area :message, class: "form-control"%>
    </div>
    <div class="card-footer">
      <%= form.submit "ตอบ", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/votes/create.js.erb
$("#vote-actions-<%=@post.id%> .score").text(<%= @post.score%>)